apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-v2
  namespace: superheros
  labels:
    app: catalog
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
      version: v2
  template:
    metadata:
      labels:
        app: catalog
        version: v2
    spec:
      containers:
      - name: catalog
        image: dockergc00/superheros-catalog:v2
        ports:
        - containerPort: 8080
