version: "3.9"

services:
  catalog:
    image: dockergc00/catalog:local
    container_name: catalog
    ports:
      - "8081:8081"
    networks:
      - supernet

  inventory:
    image: dockergc00/inventory:local
    container_name: inventory
    ports:
      - "8083:8083"
    networks:
      - supernet

  payment:
    image: dockergc00/payment:local
    container_name: payment
    ports:
      - "8084:8084"
    networks:
      - supernet

  orders:
    image: dockergc00/orders:local
    container_name: orders
    ports:
      - "8082:8082"
    networks:
      - supernet
    environment:
      - CATALOG_URL=http://catalog:8081
      - INVENTORY_URL=http://inventory:8083
      - PAYMENT_URL=http://payment:8084

  frontend:
    image: dockergc00/frontend:local
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - supernet
    environment:
      - VITE_CATALOG_API=http://catalog:8081
      - VITE_ORDERS_API=http://orders:8082
      - VITE_INVENTORY_API=http://inventory:8083
      - VITE_PAYMENT_API=http://payment:8084

networks:
  supernet:
    driver: bridge
