apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: catalog
  namespace: superheros
spec:
  hosts:
    - catalog
    - catalog.superheros.svc.cluster.local

  http:
    - match:
        - uri:
            prefix: /api/catalog
      rewrite:
        uri: /
      route:
        - destination:
            host: catalog.superheros.svc.cluster.local
            subset: v1
          weight: 50
        - destination:
            host: catalog.superheros.svc.cluster.local
            subset: v2
          weight: 50
