apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend
  namespace: superheros
spec:
  hosts:
  - "*"
  gateways:
  - superheros-gateway
  http:
  - route:
    - destination:
        host: frontend.superheros.svc.cluster.local
        subset: v1
      weight: 50
    - destination:
        host: frontend.superheros.svc.cluster.local
        subset: v2
      weight: 50
