apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: catalog
  namespace: {{ .Values.namespace }}
spec:
  host: catalog
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
{{- range $ver := .Values.services.catalog.versions }}
    - name: {{ $ver.name }}
      labels:
        app: catalog
        version: {{ $ver.name }}
{{- end }}
