apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: catalog
  namespace: {{ .Values.namespace }}
spec:
  host: catalog
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: v1
      labels:
        app: catalog
        version: v1
    - name: v2
      labels:
        app: catalog
        version: v2
    - name: v3
      labels:
        app: catalog
        version: v3
