namespace:
  name: superheros
image:
  registry: docker.io/dockergc00
services:
  frontend:
    enabled: true
    image: superheros-frontend
    replicas: 1
    tag: v1-23b0120
    port: 80
  catalog:
    enabled: true
    image: superheros-catalog
    port: 8081
    versions:
      - name: superheros-catalog
        tag: v1-e5dd632
        replicas: 1
        trafficWeight: 40
      - name: superheros-catalog
        tag: v2-e5dd632
        replicas: 1
        trafficWeight: 30
      - name: superheros-catalog
        tag: v3-e5dd632
        replicas: 1
        trafficWeight: 30
  inventory:
    enabled: true
    image: superheros-inventory
    tag: v1-f34b8a7
    port: 8083
  orders:
    enabled: true
    image: superheros-orders
    tag: v1-f4efa51
    port: 8082
  payment:
    enabled: true
    image: superheros-payment
    tag: v1-9a871ff
    port: 8084
