name: CD - Catalog (GitOps)

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["CI - Catalog (v1 v2 v3)"]
    types:
      - completed

jobs:
  update-helm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set commit SHA
        run: |
          echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Update Helm values (catalog)
        run: |
          yq -i '.services.catalog.versions[0].tag = "v1-${SHA}"' \
            gc-industries-devops-superheros/infra/helm/values.yaml

          yq -i '.services.catalog.versions[1].tag = "v2-${SHA}"' \
            gc-industries-devops-superheros/infra/helm/values.yaml

          yq -i '.services.catalog.versions[2].tag = "v3-${SHA}"' \
            gc-industries-devops-superheros/infra/helm/values.yaml

      - name: Commit & push Helm change
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "chore(cd): update catalog images ${SHA}"
          git push
