name: CD - Inventory (GitOps)

on:
  workflow_run:
    workflows: ["CI - Inventory"]
    types:
      - completed

jobs:
  update-helm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        run: |
          echo "TAG=v1-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Update Helm values (inventory)
        run: |
          yq -i '.services.inventory.tag = env(TAG)' \
            gc-industries-devops-superheros/helm/superheros/values.yaml

      - name: Commit & push Helm change
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "chore(cd): update inventory image ${TAG}"
          git push
