name: CI - Catalog (v1 v2 v3)

on:
  push:
    branches:
      - main
    paths:
      - gc-industries-devops-superheros/services/catalog/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: gc-industries-devops-superheros

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Catalog v1
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/superheros-catalog
          TAG=v1-${GITHUB_SHA::7}
          docker build -t $IMAGE:$TAG services/catalog
          docker push $IMAGE:$TAG

      - name: Build & Push Catalog v2
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/superheros-catalog
          TAG=v2-${GITHUB_SHA::7}
          docker build -t $IMAGE:$TAG services/catalog
          docker push $IMAGE:$TAG

      - name: Build & Push Catalog v3
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/superheros-catalog
          TAG=v3-${GITHUB_SHA::7}
          docker build -t $IMAGE:$TAG services/catalog
          docker push $IMAGE:$TAG